language: bash
services: docker

env:
  - VERSION=master
  - VERSION=8.10
  - VERSION=7.10
  - VERSION=6.0

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="nuxeo/nuxeo:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
